# Generated by Django 4.1.2 on 2023-09-14 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archetype',
            options={'verbose_name': 'Архетип', 'verbose_name_plural': 'Архетипы'},
        ),
        migrations.AlterModelOptions(
            name='сompatibility',
            options={'verbose_name': 'Совместимость', 'verbose_name_plural': 'Совместимость архетипов'},
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображение к варианту ответа'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='first_arch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_arch_answer', to='main.archetype', verbose_name='Первый ахретип'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='second_arch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_arch_answer', to='main.archetype', verbose_name='Второй ахретип'),
        ),
        migrations.AlterField(
            model_name='сompatibility',
            name='first_user_description',
            field=models.TextField(verbose_name='Отчет о совместимости для первого пользователя'),
        ),
    ]
