# Generated by Django 4.1.2 on 2023-09-14 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_archetype_options_alter_сompatibility_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сompatibility',
            name='first_arch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_arch_compat', to='main.archetype', verbose_name='Первый архетип'),
        ),
        migrations.AlterField(
            model_name='сompatibility',
            name='second_arch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_arch_compat', to='main.archetype', verbose_name='Второй архетип'),
        ),
    ]
