# Generated by Django 4.1.2 on 2023-09-17 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_сompatibility_first_arch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сompatibility',
            name='cap_index',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='ID пользователя в телеграм')),
                ('user_name', models.CharField(max_length=255, null=True, verbose_name='Имя пользователя')),
                ('signup_date', models.DateTimeField(auto_now=True, verbose_name='Дата регистрации пользователя')),
                ('archetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_arch', to='main.archetype', verbose_name='Архетип пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
