# Generated by Django 4.1.2 on 2023-09-19 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_сompatibility_cap_index_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='ID пользователя')),
                ('user_name', models.CharField(max_length=255, null=True, verbose_name='Имя пользователя')),
                ('start_date', models.DateTimeField(auto_now=True, verbose_name='Дата начала подписки')),
                ('end_date', models.DateTimeField(auto_now=True, verbose_name='Дата завершения подписки')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='first_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_arch', to='main.user', verbose_name='ID пригласившего пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='free_limits',
            field=models.IntegerField(null=True, verbose_name='Бесплатные запросы'),
        ),
        migrations.AddField(
            model_name='user',
            name='payed_limits',
            field=models.IntegerField(null=True, verbose_name='Оплаченные запросы'),
        ),
    ]
